trigger:
  - master

resources:
  repositories:
  - repository: AzureDevOps
    type: git
    endpoint: AzureDevOps
    name: AzureDevOps/AzureDevOps

stages:
- stage: Example
  jobs:
  - job: FailNoTag
    displayName: FailNoTagDisplayName
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - task: Docker@2
        inputs:
          container: postgres:14.2

  - job: PassDigest
    pool:
      vmImage: 'ubuntu-18.04'
    container:
      image: node:14.16

    steps:
      - script: printenv

jobs:
- job: Extreme
  container: 
    image: node:14.13
  pool:
    vmImage: windows-latest
  steps:
  - script: echo "Running in a container based on myorg/mycontainer:1.0"
- job: Super
  container:
    image: node:14.12
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: echo "Running in a container based on node:14.16"
